### ISSUE TITLE
Firebase common ver 22 is incompatible with Courier

### ISSUE THREAD

**Issue by lance0428** [trycourier/courier-android#26]
We were attempting to upgrade our Firebase version in our app today from `33.15.0` to `34.1.0`. This new bom uses `com.google.firebase:firebase-common:22` that includes changes for Google's initiative to move a lot of the ktx helpers into the main packages ([more](https://firebase.google.com/docs/android/kotlin-migration)). It seems they have removed `com.google.firebase.ktx.Firebase` and they want you to use `com.google.firebase.Firebase` directly.

We are getting `NoClassDefFoundError` errors that are crashing our app.

```
15:15:45.389  E  FATAL EXCEPTION: main (Ask Gemini)
                 Process: co.betterup.betterup.debug, PID: 23898
                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/ktx/Firebase;
                 	at com.courier.android.modules.PushModuleKt$getFcmToken$2.invokeSuspend(PushModule.kt:42)
                 	at com.courier.android.modules.PushModuleKt$getFcmToken$2.invoke(Unknown Source:8)
```

**Comment by mikemilla** [comment]
@lance0428 still working on getting this right, more challenging than you'd think because all out dependencies work with 1.7.20 of kotlin. Latest firebase messaging requires 1.9.0 among other changes.

Figured I'd send an update.

**Comment by YiHaoHuang** [comment]
Just wanted to bump this for visibility. We just hit the same NoClassDefFoundError: com/google/firebase/ktx/Firebase after pulling in a transitive dependency that brought our Firebase BoM forward.

**Workaround that's working for us**: pinning the affected Firebase -ktx artifacts to the last versions that still ship the deprecated com.google.firebase.ktx.* classes Courier references, so the deprecated symbols remain on the classpath even with the newer BoM. That unblocks us, but it's brittle — we can't hold those -ktx versions back forever, and any consumer adding a dep that pulls a newer Firebase transitively will hit this.

**Comment by mikemilla** [comment]
@YiHaoHuang this is support in the `courier-android` package now!

We've decouple the kit from Firebase, here is what you will need to do.
https://github.com/trycourier/courier-android/blob/main/Docs/PushNotifications.md#2-sync-push-notification-tokens

If you need anything else please let us know! Sorry this took so long. Lots of upgrades going on over here!
